id: 3
pretrained: Null
model:
    name:                       bert_multi
    args:
        nclasses:               5
        freeze:                 True
optimizer:
    name:                       Adam
    args:
        lr:                     0.00001
loss:
    name:                       CrossEntropyLoss
    args:
        ignore_index:           5
metric:
    -   name:                   Accuracy
        args:                   Null
    -   name:                   ConfusionMatrix
        args:                       
            nclasses:           5

scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5
        patience:                 5 
        verbose:                  True         
dataset:
    train:
        name: shopee_bert_multi
        args:
            data_root_dir:      ./data/clean/full/         
            is_train:           True  
        loader:
            name: shopee_loader
            args:
                batch_size:     32
                shuffle:        True
    val:
        name: shopee_bert_multi
        args:
            data_root_dir:      ./data/clean/full/          
            is_train:           False  
        loader:
            name: shopee_loader
            args:
                batch_size:     32
trainer: 
    nepochs: 50
    cp_dir: ./cp
    val_step: 1
    log_step: 1
